package config

import (
	"strings"

	"github.com/samber/lo"
)

var (
	NodeMap = map[string]string{
		"babel": "Project Babel", "v2ex": "V2EX", "olivida": "OLIVIDA", "music": "音乐", "movie": "电影",
		"earth": "地球", "bfbc2": "BFBC2", "iphone": "iPhone", "ipad": "iPad", "mbp": "MacBook Pro", "linux": "Linux",
		"qna": "问与答", "idev": "iDev", "gae": "Google App Engine", "twitter": "Twitter", "share": "分享发现",
		"create": "分享创造", "shanghai": "上海", "beijing": "北京", "guangzhou": "广州", "shenzhen": "深圳",
		"macos": "macOS", "kk": "Kevin Kelly", "math": "数学", "lijiang": "丽江", "hangzhou": "杭州",
		"photograph": "摄影", "picky": "Project Picky", "guilin": "桂林", "chengdu": "成都", "chongqing": "重庆",
		"nds": "NDS", "ps3": "PlayStation 3", "xbox360": "Xbox 360", "psp": "PSP", "wii": "Wii", "kindle": "Kindle",
		"tokyo": "东京", "android": "Android", "imac": "iMac", "kunming": "昆明", "guiyang": "贵阳", "jobs": "酷工作",
		"tianjin": "天津", "re5": "Resident Evil 5", "icode": "iCode", "redis": "Redis", "tv": "剧集", "steam": "Steam",
		"nyc": "New York", "nosql": "NoSQL", "hardware": "硬件", "autistic": "自言自语", "adobe": "Adobe",
		"games": "游戏", "internet": "互联网", "c": "C", "photoshop": "Photoshop", "random": "随想", "html": "HTML",
		"mysql": "MySQL", "php": "PHP", "java": "Java", "youtube": "YouTube", "google": "Google", "3g": "3G",
		"taste": "美酒与美食", "iad": "iAd", "all4all": "二手交易", "ilife": "iLife", "iwork": "iWork", "vpn": "VPN",
		"typography": "字体排印", "macpro": "Mac Pro", "uniqlo": "UNIQLO", "levis": "Levi's", "gstar": "G-Star",
		"converse": "Converse", "server": "服务器", "wuhan": "武汉", "ror": "Ruby on Rails", "nginx": "NGINX",
		"macmini": "Mac mini", "macbook": "MacBook", "moh": "Medal of Honor", "vimeo": "Vimeo",
		"wordpress": "WordPress", "muji": "无印良品", "4sq": "foursquare", "python": "Python", "firefox": "Firefox",
		"chrome": "Chrome", "safari": "Safari", "acg": "ACG", "plant": "植物", "feedback": "反馈", "opera": "Opera",
		"sc2": "StarCraft 2", "in": "分享邀请码", "openstack": "OpenStack", "animal": "动物", "git": "git",
		"blogger": "Blogger", "cloud": "云计算", "bzr": "bzr", "baby": "Baby", "fml": "糗事分享", "bb": "宽带症候群",
		"search": "搜索引擎技术研究", "oauth": "OAuth", "reading": "阅读", "x": "翻译", "hongkong": "香港",
		"macau": "澳门", "bayarea": "湾区", "wikipedia": "Wikipedia", "berlin": "Berlin", "writing": "文学",
		"gomoku": "五子棋", "digg": "Digg", "jiong": "囧", "starter": "创造者", "perl": "Perl", "scala": "Scala",
		"eco": "经济", "edu": "教育", "io": "io", "apache": "Apache", "couchdb": "CouchDB", "boardgame": "桌游",
		"imarketing": "iMarketing", "arcade": "街机游戏", "show": "晒晒更健康", "zh": "中文", "http": "HTTP",
		"dos": "DOS", "re": "正则表达式", "taipei": "台北", "css": "CSS", "newbalance": "New Balance", "nike": "Nike",
		"adidas": "Adidas", "otaku": "宅", "dell": "Dell", "livid": "Livid", "js": "JavaScript", "lua": "Lua",
		"pointless": "无要点", "treehole": "树洞", "tengzhou": "滕州", "xiamen": "厦门", "hohhot": "呼和浩特",
		"blackberry": "BlackBerry", "nanjing": "南京", "xian": "西安", "daqing": "大庆", "eggpain": "强迫症",
		"80days": "80 天环游地球", "ss": "沉默的螺旋", "diesel": "Diesel", "pixelart": "像素艺术", "hadoop": "Hadoop",
		"mapreduce": "MapReduce", "sanya": "三亚", "haikou": "海口", "zhuhai": "珠海", "cocos2d": "cocos2d",
		"ipod": "iPod", "appletv": "Apple TV", "matrix": "Matrix", "invest": "投资", "igame": "iGame",
		"accessory": "配件", "erlang": "Erlang", "dalian": "大连", "car": "汽车", "copter": "直升机",
		"linkinpark": "Linkin Park", "gyyz": "贵阳一中", "ynsdfz": "云南师大附中", "travel": "旅行",
		"opensolaris": "OpenSolaris", "moinmoin": "MoinMoin", "apple": "Apple", "bluray": "Blu-ray", "assembly": "汇编",
		"dream": "梦", "inception": "Inception", "ssh": "SSH", "outsourcing": "外包", "bmw": "BMW", "camino": "Camino",
		"mobileme": "MobileMe", "pinkfloyd": "Pink Floyd", "u2": "U2", "nirvana": "Nirvana", "rammstein": "Rammstein",
		"flash": "Flash", "dns": "DNS", "london": "London", "macgaming": "Mac 游戏", "mileage": "行程控",
		"wuxi": "无锡", "xen": "Xen", "creditcard": "信用卡", "zhengzhou": "郑州", "riak": "Riak", "linode": "Linode",
		"fuzhou": "福州", "jinan": "济南", "lanzhou": "兰州", "qingdao": "青岛", "suzhou": "苏州", "yangzhou": "扬州",
		"design": "设计", "kyoto": "京都", "corsair": "海盗船", "podcast": "Podcast", "lacrimosa": "Lacrimosa",
		"ideology": "Ideology", "tc": "TechCrunch", "quora": "Quora", "rework": "REWORK", "inbox": "Inbox",
		"audi": "Audi", "autocad": "AutoCAD", "diablo3": "Diablo III", "ja": "日本語", "en": "English",
		"fengshui": "风水", "iconfactory": "Iconfactory", "nokia": "Nokia", "hishim": "他他", "herher": "她她",
		"24": "24 小时", "green": "绿色低碳", "seattle": "Seattle", "gq": "GQ", "sydney": "Sydney", "changsha": "长沙",
		"lifestyle": "生活方式", "paris": "Paris", "dubai": "Dubai", "singapore": "Singapore", "mozilla": "Mozilla",
		"cod": "Call of Duty", "stop": "STOP", "whu": "武汉大学", "vim": "Vim", "lamy": "Lamy",
		"moleskine": "Moleskine", "pku": "北京大学", "tsinghua": "清华大学", "emacs": "Emacs", "sjtu": "上海交通大学",
		"sysu": "中山大学", "draw": "画画", "fcp": "Final Cut Pro", "motion": "Motion", "security": "信息安全",
		"harukimurakami": "村上春树", "thebeatles": "The Beatles", "entropy": "熵", "aden": "亚丁湾", "lotr": "指环王",
		"2012": "2012", "hsbc": "汇丰银行", "toyota": "丰田", "webos": "webOS", "standardchartered": "渣打银行",
		"citi": "花旗银行", "abnamro": "荷兰银行", "deutschebank": "德意志银行", "ubs": "瑞士银行", "lisp": "Lisp",
		"wired": "WIRED", "energy": "能源", "condenast": "Condé Nast", "samsonite": "Samsonite", "dior": "Dior",
		"omega": "OMEGA", "nfs": "Need for Speed", "ef": "EF", "textie": "Textie", "exchange": "物物交换",
		"afterdark": "天黑以后", "dropbox": "Dropbox", "bicycle": "自行车", "ikea": "宜家", "alienware": "Alienware",
		"facebook": "Facebook", "sqlite": "SQLite", "tuan": "团购", "sony": "SONY", "oslo": "Oslo",
		"stockholm": "Stockholm", "portland": "Portland", "gamedevstory": "Game Dev Story",
		"aws": "Amazon Web Services", "programmer": "程序员", "designer": "设计师", "transformers": "变形金刚",
		"cartier": "Cartier", "davidoff": "Davidoff", "gap": "Gap", "diary": "日记", "api": "API", "love": "非诚勿扰",
		"angel": "天使投资", "business": "商业模式", "mongodb": "MongoDB", "newbie": "新手求助", "ted": "TED",
		"flamewar": "水深火热", "standard": "标准", "fanfou": "饭否 API", "volkswagen": "Volkswagen", "scifi": "科幻",
		"lohas": "乐活", "wtf": "不靠谱茶话会", "528491": "528491", "lbp": "小小大星球", "3ds": "3DS",
		"bf3": "Battlefield 3", "curl": "cURL", "mba": "MacBook Air", "origin": "Origin", "asana": "Asana",
		"asdf": "asdf", "1q84": "1Q84", "adsense": "AdSense", "adwords": "AdWords", "ff": "最终幻想",
		"cuttherope": "Cut the Rope", "hm": "H&M", "killzone": "Killzone", "webmaster": "站长", "blackmagic": "黑魔法",
		"yippeearts": "Yippee Arts", "minecraft": "Minecraft", "muse": "MUSE", "leica": "莱卡", "canon": "佳能",
		"nikon": "尼康", "bento": "Bento", "instapaper": "Instapaper", "dribbble": "Dribbble", "ec": "EC",
		"dotnet": ".NET", "ontology": "本体论", "zakka": "雑貨", "loreal": "L'Oréal", "alexa": "Alexa",
		"garageband": "GarageBand", "3dsmax": "3ds Max", "lancome": "LANCÔME", "jp": "日本", "findpeople": "寻人",
		"admob": "AdMob", "windows": "Windows", "tornado": "Tornado", "path": "Path", "gw2": "Guild Wars 2",
		"chamber": "Chamber", "postgresql": "PostgreSQL", "guide": "使用指南", "ruby": "Ruby",
		"beforesunrise": "早睡早起身体好俱乐部", "portal": "Portal series", "logitech": "罗技", "amazon": "Amazon",
		"minio": "MinIO", "blog": "Blog", "irobot": "iRobot", "go": "Go 编程语言", "starbucks": "Starbucks",
		"pal": "仙剑奇侠传", "wow": "World of Warcraft", "cc": "Creative Commons", "flood": "水", "xinyu": "新余",
		"yueyang": "岳阳", "dali": "大理", "changchun": "长春", "zunyi": "遵义", "xining": "西宁", "harbin": "哈尔滨",
		"nanchang": "南昌", "baoding": "保定", "crysis": "Crysis", "wp": "Windows Phone", "arch": "Arch",
		"tongren": "铜仁", "gtd": "Getting Things Done", "opensource": "开源软件", "gcc": "GCC", "llvm": "LLVM",
		"amd": "AMD", "intel": "Intel", "nvidia": "NVIDIA", "maya": "Maya", "svelte": "Svelte", "bitcoin": "Bitcoin",
		"porsche": "Porsche", "stormwind": "Project Stormwind", "reddit": "Reddit", "oracle": "Oracle", "bing": "Bing",
		"pixelmator": "Pixelmator", "jekyll": "Jekyll", "yc": "Y Combinator", "arc": "Arc", "programming": "编程",
		"os": "操作系统", "vcs": "版本控制系统", "frameworks": "编程框架", "software": "软件", "computers": "计算机",
		"consoles": "游戏主机", "basic": "BASIC", "db": "数据库", "browsers": "浏览器", "mercurial": "Mercurial",
		"sqlserver": "SQL Server", "jquery": "jQuery", "wwdc": "WWDC", "psvita": "PlayStation Vita", "ea": "EA",
		"nintendo": "Nintendo", "icloud": "iCloud", "django": "Django", "zh2": "中二病", "1990": "1990",
		"celery": "Celery", "instagram": "Instagram", "nodejs": "Node.js", "dotcloud": "DotCloud",
		"wave": "Google Wave Protocol", "ifttt": "IFTTT", "media": "媒体", "lumix": "LUMIX", "gopro": "GoPro",
		"itunes": "iTunes", "appstore": "App Store", "tech": "科技", "rage": "RAGE", "chicago": "Chicago",
		"opengl": "OpenGL", "directx": "DirectX", "dust514": "DUST 514", "gnome": "Gnome", "dota": "DotA", "cdn": "CDN",
		"lol": "英雄联盟", "scrum": "Scrum", "centos": "CentOS", "gamedev": "游戏开发", "udk": "Unreal Development Kit",
		"vmware": "VMware", "glassfish": "GlassFish", "jinja": "Jinja", "monocle": "Monocle", "unity": "UNITY",
		"blender": "Blender", "3d": "3D", "zeppelin": "Project Zeppelin", "flask": "Flask", "iama": "I Am A",
		"razer": "Razer", "netbeans": "NetBeans", "running": "跑步", "clojure": "Clojure", "coldfusion": "ColdFusion",
		"whatsapp": "WhatsApp", "backbone": "Backbone.js", "textmate": "TextMate", "editors": "编辑器",
		"jlu": "吉林大学", "500px": "500px", "pinterest": "Pinterest", "sae": "Sina App Engine", "svn": "Subversion",
		"global": "海外留学", "air": "空气", "lego": "LEGO", "asteroid": "Project Asteroid", "inc": "公司运营",
		"alipay": "支付宝", "xcode": "Xcode", "skyrim": "上古卷轴 V", "mgs": "Metal Gear Solid", "homebrew": "Homebrew",
		"rabbitmq": "RabbitMQ", "gossip": "业界八卦", "gta": "Grand Theft Auto", "starwars": "星球大战",
		"indesign": "InDesign", "illustrator": "Illustrator", "moe": "分享萌物", "fling": "Fling", "pogo": "Pogo",
		"freebsd": "FreeBSD", "video": "视频技术", "trello": "Trello", "lighttpd": "Lighttpd", "arduino": "Arduino",
		"cv": "求职", "gt": "Gran Turismo", "pet": "宠物", "charles": "Charles", "eve": "EVE", "wacom": "Wacom",
		"markdown": "Markdown", "zope": "Zope", "ibook": "iBook", "weibo": "微博", "galaxy": "Project Galaxy",
		"museum": "Project Museum", "ideas": "奇思妙想", "ustc": "中国科学技术大学", "closed": "关闭交易",
		"bike": "骑行", "0x10c": "0x10c", "mushroom": "蘑菇", "paper": "Paper", "homme": "Homme", "dn": "域名",
		"ruofan": "若饭", "techstars": "TechStars", "meteor": "Meteor", "haskell": "Haskell",
		"sqlalchemy": "SQLAlchemy", "storm": "Storm", "soccer": "绿茵场", "sublime": "Sublime Text", "ubuntu": "Ubuntu",
		"fedora": "Fedora", "gentoo": "Gentoo", "la": "Los Angeles", "evernote": "Evernote", "tangcha": "唐茶",
		"sandbox": "沙盒", "downvoted": "Down Voted", "reprocess": "信息处理中心", "guitar": "吉他", "time": "时间",
		"visa": "签证", "dev": "Dev", "lightroom": "Lightroom", "aperture": "Aperture", "free": "免费赠送",
		"stripe": "Stripe", "coffee": "咖啡", "gwan": "G-WAN", "squid": "Squid", "velocity": "Velocity", "life": "生活",
		"europe": "欧洲", "uk": "英国", "us": "美国", "se": "瑞典", "de": "德国", "openbsd": "OpenBSD",
		"haproxy": "HAProxy", "sd": "Stable Diffusion", "c3edge": "C3Edge", "netlify": "Netlify", "ssl": "SSL",
		"rrdtool": "RRDtool", "xenserver": "XenServer", "puppet": "Puppet", "doitim": "Doit.im",
		"cloudstack": "CloudStack", "simcity": "SimCity", "varnish": "Varnish", "rq": "RQ", "kde": "KDE",
		"hawken": "Hawken", "survey": "调查", "ios": "iOS", "azure": "Microsoft Azure", "iis": "IIS",
		"newrelic": "New Relic", "startupvisa": "Startup Visa", "make": "make", "oreilly": "O'Reilly",
		"delphi": "Delphi", "ningbo": "宁波", "4g": "4G", "memsql": "MemSQL", "openvz": "OpenVZ", "nba": "NBA",
		"edgecast": "EdgeCast", "fitbit": "Fitbit", "couchbase": "Couchbase", "cassandra": "Cassandra",
		"hbase": "HBase", "lucene": "Lucene", "erp": "ERP", "cisco": "Cisco", "solr": "Solr", "sv": "硅谷",
		"openshift": "OpenShift", "xindanwei": "新单位", "orca": "ORCA", "meizu": "魅族", "naq": "不是问题的问题",
		"computervision": "Computer vision", "pasadena": "Pasadena", "olympics": "奥运会",
		"stackoverflow": "Stack Overflow", "nexus": "Nexus", "monthly": "每个月都会出现的那种主题", "appnet": "App.net",
		"elasticsearch": "Elasticsearch", "santamonica": "Santa Monica", "passenger": "Phusion Passenger",
		"anno": "Anno", "chocolat": "Chocolat", "sanfrancisco": "San Francisco", "bigdata": "Big Data",
		"devops": "DevOps", "virtualbox": "VirtualBox", "cherokee": "Cherokee", "openra": "OpenRA", "chef": "Chef",
		"wesnoth": "Battle for Wesnoth", "irc": "IRC", "munin": "Munin", "solaris": "Solaris", "heroku": "Heroku",
		"ingress": "Ingress", "lasvegas": "Las Vegas", "netbsd": "NetBSD", "opennebula": "OpenNebula",
		"juniper": "Juniper", "ceph": "Ceph", "swift": "Swift", "splunk": "Splunk", "stunnel": "stunnel",
		"california": "California", "smartos": "SmartOS", "zfs": "ZFS", "atlassian": "Atlassian", "sdn": "SDN",
		"unix": "Unix", "coc": "Clash of Clans", "shadowsocks": "shadowsocks", "wechat": "微信", "pi": "Raspberry Pi",
		"square": "Square", "opensuse": "openSUSE", "vps": "VPS", "lxc": "LXC", "confluence": "Confluence",
		"wiki": "Wiki", "plone": "Plone", "sphinx": "Sphinx", "rst": "reStructuredText", "hubot": "HUBOT",
		"vagrant": "Vagrant", "ansible": "Ansible", "ats": "Apache Traffic Server", "ca": "加拿大", "cn": "中国",
		"mx": "墨西哥", "kr": "韩国", "asia": "亚洲", "discourse": "Discourse", "fluentd": "Fluentd",
		"debian": "Debian", "alfred": "Alfred", "re6": "Resident Evil 6", "cloudera": "Cloudera",
		"ps4": "PlayStation 4", "immt": "我叫 MT", "euca": "Eucalyptus", "ml": "机器学习", "tw": "台湾",
		"paypal": "PayPal", "openresty": "OpenResty", "stash": "Stash", "xehost": "XeHost", "voltdb": "VoltDB",
		"ovh": "OVH", "bf4": "Battlefield 4", "smartisanos": "Smartisan OS", "ssd": "SSD", "aerofs": "AeroFS",
		"miui": "MIUI", "feo": "前端优化", "sailfish": "Sailfish", "mechanical": "机械键盘", "line": "LINE",
		"spark": "Spark", "glass": "Google Glass", "hardcore": "发烧友", "emc": "EMC", "microsoft": "微软",
		"fit": "健康", "webrtc": "WebRTC", "braun": "Braun", "soho": "SOHO", "4k": "4K", "offworld": "重口味问与答",
		"german": "德语", "duolingo": "Duolingo", "core": "Core", "lvm": "LVM", "jira": "Jira", "bash": "Bash",
		"oculusvr": "Oculus VR", "btsync": "BTSync", "itransfer": "iTransfer", "zed": "Zed", "docker": "Docker",
		"hyperloop": "Hyperloop", "bootstrap": "Bootstrap", "zookeeper": "ZooKeeper", "ie": "IE", "pdns": "PowerDNS",
		"localllm": "Local LLM", "salt": "Salt Stack", "sap": "SAP", "documentary": "纪录片", "taobao": "淘宝",
		"dogma": "Dogma", "diamondbar": "Diamond Bar", "rowlandheights": "Rowland Heights", "walnut": "Walnut",
		"borderlands": "Borderlands", "ghost": "Ghost", "laiwang": "来往", "nissan": "Nissan", "chevrolet": "Chevrolet",
		"oversea": "海外运营", "hearthstone": "Hearthstone", "hos": "Heroes of the Storm", "projects": "项目管理",
		"bns": "剑灵", "fdb": "FoundationDB", "dart": "Dart", "xboxone": "Xbox One", "hermanmiller": "Herman Miller",
		"ripple": "Ripple", "boinc": "BOINC", "deals": "优惠信息", "wiiu": "Wii U", "mint": "Linux Mint",
		"forex": "外汇交易", "warcraft": "魔兽争霸", "modo": "MODO", "lynda": "Lynda", "mudbox": "Mudbox",
		"libido": "情感问题", "titanfall": "Titanfall", "percona": "Percona", "kvm": "KVM", "sentry": "Sentry",
		"playrust": "生存游戏 Rust", "serf": "Serf", "boston": "Boston", "coreos": "CoreOS", "sports": "体育运动",
		"pwa": "PWA", "opencl": "OpenCL", "webp": "WebP", "wagas": "Wagas", "mbti": "MBTI", "career": "职场话题",
		"ibeacon": "iBeacon", "github": "GitHub", "atom": "Atom", "bose": "Bose", "sputnik": "Sputnik",
		"powershell": "PowerShell", "seo": "搜索引擎优化", "ace": "Ace", "solarcity": "SolarCity", "spacex": "SpaceX",
		"hack": "Hack", "avocado": "Avocado", "sketch": "Sketch", "rfc": "RFC", "medium": "Medium",
		"samsung": "Samsung", "tarsnap": "Tarsnap", "shenyang": "沈阳", "ssdb": "SSDB", "rust": "Rust",
		"fe": "前端开发", "servo": "Servo", "phabricator": "Phabricator", "bong": "bong", "leancloud": "LeanCloud",
		"thinkpad": "ThinkPad", "solar": "太阳能", "log": "日志处理", "ielts": "雅思", "whv": "工作假期签证",
		"syslog": "Syslog", "uber": "Uber", "twitch": "Twitch", "mmm": "买买买", "notes": "Notes", "openwrt": "OpenWrt",
		"ford": "福特", "mb": "奔驰", "bfh": "Battlefield Hardline", "simracing": "模拟驾驶", "oneapm": "OneAPM",
		"drafts": "草稿箱", "depression": "抑郁症", "angular": "Angular", "tesla": "Tesla", "destiny": "Destiny",
		"waze": "Waze", "factorio": "Factorio", "watch": " WATCH", "corvette": "Corvette", "gotye": "亲加通讯云",
		"fir": "fir.im", "coding": "Coding", "router": "路由器", "gdg": "GDG", "pingpp": "Ping++", "goban": "围棋",
		"cheap": "穷", "pm": "产品经理茶话会", "2015": "2015", "webgl": "WebGL", "gitcafe": "GitCafe",
		"learn": "学点什么", "xiaomi": "小米", "dji": "DJI", "telegram": "Telegram", "react": "React",
		"dotgeek": "DotGeek", "fitness": "健身", "wunderlist": "奇妙清单", "spg": "SPG", "pay": " Pay",
		"shokunin": "职人", "ionic": "Ionic", "outdoor": "户外运动", "rethinkdb": "RethinkDB", "mobiledev": "移动开发",
		"barcelona": "Barcelona", "drones": "无人机", "status": "V2EX 站点状态", "jiankongbao": "监控宝",
		"polymer": "Polymer", "mesos": "Mesos", "udacity": "Udacity", "changes": "V2EX 站点更新",
		"airmech": "AirMech Arena", "besiege": "Besiege", "u": "大学", "pronunciation": "发音",
		"imperfect": "这个世界不完美", "dashcam": "行车记录仪", "surface": "Surface", "qt": "Qt", "promotions": "推广",
		"however": "然而并没有", "synology": "Synology", "vscode": "Visual Studio Code", "cement": "Cement",
		"smartisan": "锤子手机", "earphone": "耳机", "smokeping": "SmokePing", "elixir": "Elixir 编程语言",
		"hubspot": "HubSpot", "tvos": "tvOS", "catchpoint": "Catchpoint", "rpgmaker": "RPG Maker", "bgp": "BGP",
		"excel": "Excel", "soylent": "Soylent", "touhou": "东方 Project", "vue": "Vue.js", "surge": "Surge",
		"nlp": "自然语言处理", "koukaku": "Ghost in the Shell", "2016": "2016", "tmux": "tmux", "iceland": "冰岛",
		"processing": "Processing", "ivalice": "Ivalice", "iray": "iray", "edge": "Edge", "cg": "CG",
		"mentalray": "mental ray", "stingray": "Stingray", "launchbar": "LaunchBar", "cuda": "CUDA",
		"wilddog": "野狗实时通讯云", "khan": "可汗学院", "otto": "Otto", "civ": "文明系列", "motorsport": "汽车运动",
		"monetdb": "MonetDB", "xcom": "XCOM", "caddy": "Caddy", "firebase": "Firebase", "vr": "虚拟现实",
		"1984": "1984", "hls": "HLS", "wubi": "五笔字型输入法", "ffmpeg": "FFmpeg", "pgyer": "蒲公英",
		"jetbrains": "JetBrains", "overwatch": "Overwatch", "cardboard": "Cardboard", "obs": "OBS", "c9": "Cloud9",
		"bf1": "Battlefield 1", "hyper": "Hyper_", "hexo": "Hexo", "codemirror": "CodeMirror", "rog": "玩家国度",
		"asus": "华硕", "cmb": "招商银行", "keybase": "Keybase", "ime": "输入法", "pokemon": "精灵宝可梦",
		"meet": "创业组队", "gis": "地理信息系统", "metal": "Metal", "france": "法国", "remodel": "装修",
		"vive": "Vive", "modsecurity": "ModSecurity", "monero": "Monero", "discord": "Discord", "influxdb": "InfluxDB",
		"zhihu": "知乎", "gts": "全球工单系统", "iot": "物联网", "gcloud": "Google Cloud", "rime": "中州韻",
		"wargaming": "Wargaming", "gitlab": "GitLab", "gitbook": "GitBook", "pomodoro": "番茄工作法",
		"mermaid": "Mermaid", "stats": "统计学", "pixel": "Pixel", "nas": "NAS", "wireshark": "Wireshark",
		"daocloud": "DaoCloud", "rescuetime": "RescueTime", "huawei": "华为", "algorithm": "算法",
		"electron": "Electron", "daydream": "Daydream", "amp": "AMP", "2017": "2017", "switch": "Nintendo Switch",
		"kirby": "Kirby", "nes": "NES", "retro": "怀旧游戏", "snes": "SNES", "mactype": "MacType", "hue": "Hue",
		"tamiya": "田宫模型", "memcached": "memcached", "zelda": "塞尔达传说", "retroarch": "RetroArch",
		"immigration": "移民", "algolia": "Algolia", "vivaldi": "Vivaldi", "amiibo": "Amiibo",
		"tensorflow": "TensorFlow", "kyototycoon": "Kyoto Tycoon", "quip": "Quip", "igetget": "得到",
		"racket": "Racket", "ubnt": "UBNT", "kafka": "Kafka", "5v5": "王者荣耀", "kotlin": "Kotlin",
		"ohno": "请不要再发这样的文章", "pytest": "pytest", "serverless": "Serverless", "alphago": "AlphaGo",
		"irvine": "Irvine", "webpack": "webpack", "arkit": "ARKit", "coreml": "Core ML", "musickit": "MusicKit",
		"homepod": "HomePod", "keras": "Keras", "caffe": "Caffe", "torch": "Torch", "jupyter": "Jupyter",
		"scikit": "scikit-learn", "theano": "Theano", "msoffice": "Microsoft Office", "smarthome": "智能家电",
		"logstash": "Logstash", "starcraft": "星际争霸", "kibana": "Kibana", "pubg": "PUBG", "csharp": "C#",
		"emoji": "Emoji", "ada": "ADA", "homekit": "HomeKit", "2018": "2018", "naturalist": "博物学", "ipfs": "IPFS",
		"upyun": "又拍云", "jd": "京东", "timescale": "Timescale", "bitbucket": "Bitbucket", "fortnite": "Fortnite",
		"blockchain": "区块链", "qi": "Qi 无线充电", "webdev": "Web Dev", "netflix": "Netflix", "ucla": "UCLA",
		"ipv6": "IPv6", "5g": "5G", "play": "Google Play", "mastodon": "Mastodon", "grafana": "Grafana",
		"flutter": "Flutter", "spotify": "Spotify", "turi": "Turi", "succulents": "多肉植物", "onmyoji": "阴阳师",
		"mec": "MEC", "danshari": "断舍离", "ev": "电动汽车", "taiwu": "太吾绘卷", "airbnb": "Airbnb",
		"bfv": "Battlefield V", "bf": "Battlefield 系列", "k8s": "Kubernetes", "leetcode": "LeetCode",
		"clojurescript": "ClojureScript", "2019": "2019", "bujo": "子弹笔记", "apex": "Apex Legends",
		"stadia": "Stadia", "tex": "TeX", "typescript": "TypeScript", "libra": "Libra", "cloudflare": "Cloudflare",
		"weekly": "写周报", "remote": "远程工作", "terraform": "Terraform", "vtuber": "Virtual YouTubers",
		"jsonfeed": "JSON Feed", "rss": "RSS", "quake": "雷神之锤系列", "darkmode": "夜间模式",
		"applearcade": "Apple Arcade", "zsh": "Z shell", "wg": "WireGuard", "ws": "WebSocket", "meraki": "Meraki",
		"cpp": "C++", "objc": "Objective-C", "nebula": "Nebula", "2020": "2020", "graphql": "GraphQL",
		"wenyan": "文言文编程语言", "testflight": "TestFlight", "bilibili": "哔哩哔哩", "miracleplus": "奇绩创坛",
		"terminal": "Terminal", "ipados": "iPadOS", "watchos": "watchOS", "ps5": "PlayStation 5", "neovim": "Neovim",
		"notion": "Notion", "busuu": "Busuu", "godot": "Godot", "pygame": "PyGame", "msfs": "微软飞行模拟",
		"ac": "动物之森", "alpine": "Alpine Linux", "ish": "iSH", "vapor": "Vapor", "figma": "Figma",
		"2077": "赛博朋克 2077", "2021": "2021", "eagle": "Eagle", "brave": "Brave", "dyson": "戴森球计划",
		"ifix": "云修电脑", "embedded": "嵌入式开发", "gamedb": "GameDB", "nextjs": "Next.js", "nuxtjs": "Nuxt.js",
		"dallas": "Dallas", "dune": "沙丘", "clickhouse": "ClickHouse", "diablo2": "Diablo II",
		"copilot": "GitHub Copilot", "taskade": "Taskade", "airpods": "AirPods", "psychology": "心理学",
		"terraria": "泰拉瑞亚", "opencv": "OpenCV", "vercel": "Vercel", "web3": "Web3", "nft": "NFT",
		"ethereum": "以太坊", "v2exapi": "V2EX API", "vite": "Vite", "crypto": "加密货币", "solana": "Solana",
		"solidity": "Solidity", "ton": "TON", "stc": "Starcoin", "mina": "Mina Protocol", "near": "NEAR Protocol",
		"cardano": "Cardano", "polkadot": "Polkadot", "metamask": "MetaMask", "xrc": "X Rabbits Club", "2022": "2022",
		"nixos": "NixOS", "xboxseries": "Xbox Series", "imovie": "iMovie", "zoom": "Zoom", "macstudio": "Mac Studio",
		"soulslike": "魂系游戏", "planet": "Planet", "logseq": "Logseq", "yubikey": "YubiKey", "handheld": "掌机",
		"openai": "OpenAI", "freeform": "Freeform", "nostr": "nostr", "diablo4": "Diablo IV", "macos9": "Mac OS 9",
		"cosub": "拼车", "genshin": "原神", "ens": "ENS", "vxna": "VXNA", "fishing": "钓鱼",
	}
)

var (
	OfficialNodes = []GroupNode{
		{
			Key:  "tech",
			Name: "技术",
			Nodes: []string{
				"programmer",
				"python",
				"idev",
				"android",
				"linux",
				"nodejs",
				"cloud",
				"bb",
			},
		},
		{
			Key:  "creative",
			Name: "创意",
			Nodes: []string{
				"create",
				"design",
				"ideas",
			},
		},
		{
			Key:  "play",
			Name: "好玩",
			Nodes: []string{
				"share",
				"games",
				"movie",
				"tv",
				"music",
				"travel",
				"android",
				"afterdark",
			},
		},
		{
			Key:  "apple",
			Name: "Apple",
			Nodes: []string{
				"macos",
				"iphone",
				"ipad",
				"macmini",
				"mbp",
				"imac",
				"watch",
				"apple",
			},
		},
		{
			Key:  "jobs",
			Name: "酷工作",
			Nodes: []string{
				"jobs",
				"cv",
				"career",
				"meet",
				"outsourcing",
			},
		},
		{
			Key:  "deals",
			Name: "交易",
			Nodes: []string{
				"all4all",
				"exchange",
				"free",
				"dn",
				"tuan",
			},
		},
		{
			Key:  "city",
			Name: "城市",
			Nodes: []string{
				"beijing",
				"shanghai",
				"shenzhen",
				"guangzhou",
				"hangzhou",
				"chengdu",
				"singapore",
				"nyc",
				"la",
			},
		},
		{
			Key:  "qna",
			Name: "问与答",
			Nodes: []string{
				"qna",
			},
		},
		{
			Key:  "hot",
			Name: "最热",
			Nodes: []string{
				"hot",
			},
		},
		{
			Key:  "latest",
			Name: "最新",
			Nodes: []string{
				"latest",
			},
		},
		{
			Key:  myNodes,
			Name: "*我的*",
			Nodes: []string{
				"share",
				"create",
				"qna",
				"jobs",
				"programmer",
				"career",
				"invest",
				"ideas",
				"hardware",
				"gamedev",
			},
		},
		{
			Key:  "r2",
			Name: "R2",
			Nodes: []string{
				"share",
				"create",
				"qna",
				"jobs",
				"programmer",
				"career",
				"invest",
				"ideas",
				"hardware",
			},
		},
		{
			Key:  "vxna",
			Name: "VXNA",
			Nodes: []string{
				"vxna",
				"rss",
				"planet",
				"blogger",
				"webmaster",
			},
		},
	}
)

const (
	myNodes = "my_nodes"
)

func GetGroupNode(index int) GroupNode {

	groupNode := lo.NthOr(OfficialNodes, index, OfficialNodes[0])
	if groupNode.Key == myNodes && G.MyNodes != "" {
		groupNode.Nodes = strings.Split(G.MyNodes, ",")
	}

	return groupNode
}

type GroupNode struct {
	Key   string
	Name  string
	Nodes []string
}
